add packages to install

diff --git a/aur-install b/aur-install
--- a/aur-install
+++ b/aur-install
@@ -5,16 +5,19 @@ GIT_DIR="$HOME"/Downloads/git
 echo "Did you modify /etc/makepkg.conf? [y/n]" 
 read -r input
 
-if [ "$input" = "y" ]; then
-	echo "The script will now proceed"
-elif [ "$input" = "n" ]; then
-	echo "Go edit /etc/makepkg.conf to compile packages faster. Exiting program..."
-	exit 1
-
-else
-	echo "Invalid input. Exiting program..."
-	exit 1
-fi
+case "$input" in
+	y)
+		echo "The script will now proceed"
+		;;
+	n)
+		echo "Go edit /etc/makepkg.conf to compile packages faster. Exiting program..."
+		exit 1
+		;;
+	*)
+		echo "Invalid input. Exiting program..."
+		exit 1
+		;;
+esac
 
 mkdir -p "$GIT_DIR"
 
@@ -25,4 +28,4 @@ cd "$HOME" || exit
 
 echo "Installing packages..."
 
-paru -S freetube-bin protontricks pandoc-bin shellcheck-bin rstudio-desktop-bin nwg-look-bin gruvbox-dark-gtk gruvbox-dark-icons-gtk wlogout xcursor-breeze
+paru -S freetube-bin protontricks pandoc-bin pandoc-crossref-bin shellcheck-bin rstudio-desktop-bin nwg-look-bin gruvbox-dark-gtk gruvbox-dark-icons-gtk wlogout xcursor-breeze
diff --git a/package-install b/package-install
--- a/package-install
+++ b/package-install
@@ -3,19 +3,23 @@
 echo "Main system? [y/n]"
 read -r input
 
-if [ "$input" = "y" ]; then
-	echo "Use vulkan-radeon when installing steam."
-	echo "Installing packages..."
-	sudo pacman -S steam gamescope
-elif [ "$input" = "n" ]; then
-	echo "Ignoring steam since this machine is a laptop."
-else
-	echo "Invalid input. Exiting program..."
-	exit 1
-fi
+case "$input" in
+	y)
+		echo "Use vulkan-radeon when installing steam."
+		echo "Installing packages..."
+		sudo pacman -S steam gamescope
+		;;
+	n)
+		echo "Ignoring steam since this machine is a laptop."
+		;;
+	*)
+		echo "Invalid input. Exiting program..."
+		exit 1
+		;;
+esac
 
 echo "Installing packages..."
 
-sudo pacman -S git xdg-user-dirs python-lsp-server python-server-black gvfs htop neofetch keepassxc ripgrep fd sd dust eza zellij npm man-db man-pages firefox stow thunderbird rsync marksman helix neovim jq yq qt5ct qt6ct kvantum zathura zathura-pdf-poppler texlive-latexrecommended texlive-xetex texlive-fontsrecommended mpv newsboat grim swayimg slurp clang pulsemixer swaylock tealdeer urlscan yt-dlp
+sudo pacman -S lua-language-server keychain git xdg-user-dirs python-lsp-server python-server-black gvfs htop neofetch keepassxc ripgrep fd sd dust eza zellij npm man-db man-pages firefox stow thunderbird rsync marksman helix neovim jq yq qt5ct qt6ct kvantum zathura zathura-pdf-poppler texlive-latexrecommended texlive-xetex texlive-fontsrecommended mpv newsboat grim swayimg slurp clang pulsemixer swaylock tealdeer urlscan yt-dlp
 
 xdg-user-dirs-update
